

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env               # .env dosyasını yüklemek için
    ports:
      - "8000:8000"        # API'yi 8000 numaralı porta yönlendirir
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       # .env dosyasındaki kullanıcı adı
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # .env dosyasındaki şifre
      POSTGRES_DB: ${POSTGRES_DB}           # .env dosyasındaki veritabanı adı
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
